### ISSUE TITLE
Identity flags with local evaluation

### ISSUE THREAD

**Issue by kaniak274** [Flagsmith/flagsmith-python-client#28]
Hello,
Is it possible to use `get_identity_flags` with local evaluation mode enabled?

**Comment by dabeeeenster** [comment]
It is - yes!

**Comment by dabeeeenster** [comment]
Can you provide the code that you used?

**Comment by kaniak274** [comment]
Sure!


I tried with this code:

```py
flags = Flagsmith(
    environment_key="ser.something",
    api_url="my_url",
    enable_local_evaluation=True,
)

## This returns default value from the environment
flags.get_identity_flags(identifier="someUUID", traits={}).get_feature_value("flag") 

## This returns correct value but the request to the API is required
flags._get_identity_flags_from_api(
    identifier="someUUID", traits={}
).get_feature_value("flag")
```

We are self-hosting the Flagsmith. Yesterday we updated the old bullettrain version to the newest flagsmith. Could the issue be that the update did something wrong?

**Comment by dabeeeenster** [comment]
You need to provide the traits for the identity as part of the call. With no traits you will receive default environment flags. Note the Caveats here: https://docs.flagsmith.com/clients/overview#local-evaluation-mode

**Comment by kaniak274** [comment]
Oh I was not aware about that. I will try it! Thanks!.
