### ISSUE TITLE
Method for getting Segments in the a Project

### ISSUE THREAD

**Issue by jonghyukgg** [Flagsmith/flagsmith-python-client#32]
Hi Team!

Is there any way to get Segment information through the Python SDK?
With using APIs like

- GET ​/api​/v1​/projects​/{project_pk}​/segments​/
- GET ​/api​/v1​/projects​/{project_pk}​/segments​/{id}/

I can get the list of Segments in a Project and detailed information of a Segment like traits
I found that those APIs are sufficient for my usage but I'm wondering if I can get those information also through the SDK.

Thanks!

**Comment by matthewelwell** [comment]
Hi @jonghyukgg, currently our SDKs only expose methods to use our so called 'SDK endpoints' - the ones related to retrieving flags and setting traits. 

If it's useful, however, in v3.0.0+ of the python client, when you have local evaluation enabled, you can retrieve the segments an identity is a member of by using the `get_identity_segments` method available on the client. 

Hope this helps.

**Comment by jonghyukgg** [comment]
@matthewelwell Thanks for a quick reply

I also found the `get_identity_segments` method while digging into flagsmith.py but I couldn't find a way to use it.
This method needs identifier but since I didn't set any identity thing related to the segment, which identity should I set to retrieve all segments in the project? I tried to put my emails into the identifier but it didn't work (this may be a pretty dumb question please excuse that I'm new to this platform)

Anyway I can also use APIs to retrieve all the information (segments in a project) needed

Thanks again!

**Comment by matthewelwell** [comment]
Hi @jonghyukgg, I'm afraid it's not possible to retrieve all the segments for a project from the SDK, only the matching segments for an identity. Apologies if that wasn't clear from my previous message.

**Comment by jonghyukgg** [comment]
No problem. I understood the message, just wanted to double-check. I'll close this issue for now, thanks!
