### ISSUE TITLE
Enable to set proxy

### ISSUE THREAD

**Issue by Ardnas13** [Flagsmith/flagsmith-python-client#35]
Enable to set proxy on the client. Guessing all that needs to be done is adding another attribute 'proxy', to the Flagsmith class, and then passing it to the Session object.

**Comment by matthewelwell** [comment]
I guess we would map to the functionality available in the `requests` module and allow people to set multiple proxies so perhaps an argument of `proxies` is better. 

Alternatively, we could just have a method on the client which is `add_proxy` which can then obviously be called multiple times. 

Happy to accept a PR for this.

**Comment by Ardnas13** [comment]
Great, thank you! Spontaneously, `proxies` sounds like the better choice.

**Comment by matthewelwell** [comment]
Hi @Ardnas13 , yes, that's mostly correct. It's something that is on our backlog but I cannot guarantee when we will be able to get around to implementing it. If it's something that you're keen to have available, and you're happy submitting a PR, that's probably the best course of action here.

**Comment by matthewelwell** [comment]
Hi @Ardnas13, this is now available in `3.2.0`. Documentation is updated here: https://docs.flagsmith.com/clients/server-side#configuring-the-sdk.
