### ISSUE TITLE
Provide typing stubs

### ISSUE THREAD

**Issue by khvn26** [Flagsmith/flagsmith-python-client#40]
The following is mypy output when using Flagsmith SDK in a strictly typed project:

```
src/example_service/components/flagsmith.py:3: error: Skipping analyzing "flagsmith": module is installed, but missing library stubs or py.typed marker  [import]
src/example_service/components/flagsmith.py:4: error: Skipping analyzing "flagsmith.flagsmith": module is installed, but missing library stubs or py.typed marker  [import]
```

Hopefully, shouldn't be too hard to fix. (Famous last words before jumping in the Python typing rabbit hole.)

**Comment by tushar5526** [comment]
Let's do this. Any. preference on how you want me to approach this, a single PR or different PRs module-wise?

**Comment by matthewelwell** [comment]
@tushar5526 I think a single PR should be fine, there isn't a _lot_ of code in this repository. The only thing that might provide a little painful is the typing of flag values but you can check the typing approaches in the flagsmith-engine repository for approaches on that - it looks like we're just using `typing.Any` there.

**Comment by tushar5526** [comment]
> @tushar5526 I have set up the necessary tooling and CI here: #70
> 
> Please use the `feat/mypy` branch as your base one. The acceptance criteria is the passing CI workflow.
> 
> Note that the SDK supports Python 3.8 so be sure to take it into account by using e.g. `typing.Dict` instead of `dict` and `typing_extensions.TypeGuard` instead of `typing.TypeGuard`.

Sure thanks!

**Comment by tushar5526** [comment]
Should there be type hints for tests as well?

**Comment by matthewelwell** [comment]
> Should there be type hints for tests as well?

Yes, please!

**Comment by tushar5526** [comment]
I think this one is closed!

**Comment by rolodato** [comment]
Closing, released as https://github.com/Flagsmith/flagsmith-python-client/commit/ed535ded9ba4df12e9e9eddd9093a13db31219ec in 3.6.0 :)
