### ISSUE TITLE
Feature request: load build time-cached flags

### ISSUE THREAD

**Issue by strugee** [Flagsmith/flagsmith-python-client#41]
I'd love to be able to do https://docs.flagsmith.com/guides-and-examples/integration-approaches#build-time-flag-retrieval for our backend, but it seems to be unsupported by the Flagsmith Python SDK.

I've also read https://docs.flagsmith.com/guides-and-examples/integration-approaches#caching-flags-on-a-server but would prefer to cache at build time because there are less moving parts (I don't have to worry about being able to receive webhooks from Flagsmith, and I can reuse the SDK's background update thread to retrieve from Flagsmith, instead of having to wire that up myself).

**Comment by dabeeeenster** [comment]
cc @matthewelwell @gagantrivedi @kyle-ssg Do we have an agreed spec for the static flag file format? Is it simply the output of https://github.com/Flagsmith/flagsmith-cli? If we do we can start buidling this out in our server side SDKs? 

@strugee happy to take pull requests on this!

**Comment by matthewelwell** [comment]
This is related to the issue in our main repository here: https://github.com/Flagsmith/flagsmith/issues/2024

@strugee I'd love to know if you are looking for this feature to use the python client in an 'offline mode' or as a fallback in case the SDK is unable to retrieve data from the Flagsmith API.

**Comment by matthewelwell** [comment]
This was added here: https://github.com/Flagsmith/flagsmith-python-client/pull/50.

**Comment by strugee** [comment]
@matthewelwell sorry I missed your question earlier and I'm glad to see this added 🎉 

For posterity, we wanted this for the "what if the Flagsmith API goes down" case.
