### ISSUE TITLE
Use pydantic 2

### ISSUE THREAD

**Issue by PotHix** [Flagsmith/flagsmith-python-client#55]
Our codebase uses [the latest stable version of pydantic](https://pypi.org/project/pydantic/) (2.1.1 at the moment) and we're not able to use flagsmith-python-client because one of its dependencies ([flagsmith-engine](https://github.com/Flagsmith/flagsmith-engine)) rely on pydantic <2.

I can see [there's a issue](https://github.com/Flagsmith/flagsmith-engine/issues/172) for the migration already. Any dates on how flagsmith is going to update pydantic to v2? We will be blocked until the new version is out.

**Comment by matthewelwell** [comment]
Hi @PotHix, as you've seen, the dependency is in the flagsmith-engine module. We have a PR being worked on [here](https://github.com/Flagsmith/flagsmith-engine/pull/168) which includes the update of pydantic. We're expecting to complete the PR and release it in about 2-3 weeks (as we have some other commitments until then).

**Comment by PotHix** [comment]
Thanks for replying @matthewelwell! :bow: 

That's a huge PR that is much bigger than pydantic. Is there a way to extract the pydantic part and release it before? By reading the issue, the work on pydantic itself feels quite contained (that's all I can guess with little context, though), that's why I'm asking.

If you guys are able to pull this off, it would allow us to use these two weeks to work on the development and migration, otherwise we will be mostly blocked by that.

**Comment by matthewelwell** [comment]
Hi @PotHix, yes, I appreciate that is a larger PR, however, it is closely tied to the work in that PR. I will try to extract it and put out a release sooner.

**Comment by matthewelwell** [comment]
Hi @PotHix, just a heads up here that unfortunately there seem to be some hefty breaking changes in pydantic v2, particularly around the use of the `pydantic-collections` add on. Even when simply upgrading and replacing all imports with `from pydantic.v1 ...` these errors are seemingly unavoidable.

We will of course continue to complete the upgrade, however, it is not a trivial task. I was hoping that upgrading and just using the `pydantic.v1` imports would allow us to complete the upgrade and get you guys moving but it wasn't possible unfortunately.

**Comment by PotHix** [comment]
Hey @matthewelwell! We need some confirmation that you guys can deliver it this week, otherwise, we will have to on some alternative solutions. Can you please confirm if it's going to be merged this week?

**Comment by matthewelwell** [comment]
Hi @PotHix, we're planning to look into this on Wednesday. I should be able to provide an update on Wednesday afternoon.

**Comment by matthewelwell** [comment]
Hi @PotHix, just a quick update here that we're working on this [here](https://github.com/Flagsmith/flagsmith-engine/pull/189). We're going to try and have it finished and released by the end of this week but there are a number of breaking changes migrating from pydantic 1 -> 2. Note that the engine is a core piece of technology heavily used in a lot of our services so we will need to have a thorough review and testing process. I will keep you posted on the progress.

**Comment by PotHix** [comment]
Thanks for the update @matthewelwell! If it's guaranteed to have a new version of this library until the end of the week, we can wait for that. If you feel it's uncertain, we would be in a bad situation, as we will have less than 1 week to do everything we need.

Our plan is to have the latest version of the library working on our system on Monday, so we can have the rest of the week to migrate most of our flags from a different provider.

Can we count on this plan or it's too uncertain?

**Comment by matthewelwell** [comment]
Hi @PotHix, I should have thought about this solution earlier but you can just use `flagsmith==3.2.2`as that version does not have the pydantic dependency. The interface for the client has not changed - the only feature that you would be missing is offline mode. You can work on integrating the client in the meantime and upgrade to a later version once we have completed the pydantic upgrade. How does that sound?

**Comment by PotHix** [comment]
Thanks for pointing that out! Sounds good. I did some preliminary tests, and it seems to be enough to kickstart the project.

> upgrade to a later version once we have completed the pydantic upgrade.

I'm assuming the release of the next version supporting pydantic 2 is going to happen at some point next week. Is that a correct assumption?

**Comment by dabeeeenster** [comment]
We cant/don't guarentee any release dates for anything I'm afraid @PotHix !

**Comment by PotHix** [comment]
@matthewelwell I've been facing a problem with Marshmallow when trying to test my implementation when using the version you suggested. It says:

```
ERROR tests/feature_flags/test_flagsmith.py - marshmallow.warnings.RemovedInMarshmallow4Warning: The 'default' argument to fields is deprecated. Use 'dump_default' instead.
```

Were you aware of this problem? Is there any workaround?

**Comment by matthewelwell** [comment]
@PotHix, I'm not really sure how this is throwing an `ERROR` tbh, that message is a warning only. As you can see from poetry.lock, we are using marshmallow 3.14.0 so the `default` argument still exists, it's just going to be removed in `v4`. Do you have some kind of strict warning checker in your testing environment perhaps?

**Comment by PotHix** [comment]
> Do you have some kind of strict warning checker in your testing environment perhaps?

We have! I added the warning as an exception, but it seems I did it incorrectly. Now that we considered this warning as expected, things are working again. Thanks for pointing this out!

A have another question about the older version:

>  you can just use flagsmith==3.2.2as that version does not have the pydantic dependency. The interface for the client has not changed - **the only feature that you would be missing is offline mode**.

What exactly is the offline mode you mention here? Is it the [local evaluation mode](https://docs.flagsmith.com/clients/server-side#local-evaluation-mode-network-behaviour)?

**Comment by matthewelwell** [comment]
No, local evaluation mode is available in `v3.2.2`. The offline mode I'm referring to is not yet documented since we're working on adding it to the rest of our server side SDKs. The description of the requirement can be found [here](https://github.com/Flagsmith/flagsmith/issues/2024) and the PR which added the logic is [here](https://github.com/Flagsmith/flagsmith-python-client/pull/50).

**Comment by khvn26** [comment]
Pydantic V2 support released with SDK version 3.5.0.

**Comment by levrik** [comment]
I'm basically having the exact opposite issue. I'm stuck on Pydantic v1 due to some technical issues and cannot make use of transient traits as they are only available in newer versions of the Flagsmith SDK which requires Pydantic v2. I know it's possible to use Pydantic v1 also from Pydantic v2 but another dependency I rely on doesn't support the `pydantic.v1` namespace as it relies on Pydantic v1.

**Comment by levrik** [comment]
I'm basically having the exact opposite issue. I'm stuck on Pydantic v1 due to some technical issues and cannot make use of transient traits as they are only available in newer versions of the Flagsmith SDK which requires Pydantic v2.

**Comment by matthewelwell** [comment]
Hi @levrik, thanks for getting in touch. I'm afraid that this isn't something that we would be looking to add to the client at this stage. I would suggest that you look into whatever other technical constraints are preventing the Pydantic v2 upgrade on your end. 

Otherwise, you could always fork this repository and remove the engine yourself if you deem it necessary.

**Comment by levrik** [comment]
@matthewelwell I'm trying to upgrade to Pydantic v2 for several months now already. Also a colleague has tried it but didn't manage to do it without breaking something. I guess forking this repo will be the way then.
