### ISSUE TITLE
Issue: Flagsmith Automatically Adds '/v1' Prefix

### ISSUE THREAD

**Issue by curtis-trynow-io** [Flagsmith/flagsmith-python-client#6]
Referencing https://github.com/Flagsmith/flagsmith-python-client/blob/main/flagsmith/flagsmith.py, all endpoints are automatically prefixed with `/v1`.  This differs from other Flagsmith clients which instead require you to set the full URL such as:

```
https://flagsmith.mydomain.tld/api/v1
```

As such, anyone using multiple clients for Flagsmith has to create redundant settings with and without the `/v1` to account for this difference in clients and consume them properly.  If instead the `/v1` were not automatically added, the same URL value could be used for all clients uniformly.

**Comment by curtis-trynow-io** [comment]
The fix on #7 does not agree with your other clients still.  It has a trailing slash unlike https://github.com/Flagsmith/flagsmith-nodejs-client/blob/main/flagsmith-core.js#L60.

**Comment by dabeeeenster** [comment]
Ah good catch - actually the node SDK is the odd one out - raised https://github.com/Flagsmith/flagsmith-nodejs-client/issues/19 to compensate
