### ISSUE TITLE
With `offline_mode` and `enable_local_evaluation` the polling thread is still started

### ISSUE THREAD

**Issue by AdrianB-sovo** [Flagsmith/flagsmith-python-client#66]
With `offline_mode` and `enable_local_evaluation` the polling thread is started, but we probably don't want that, since the environment will be stored in the `offline_handler` anyway.

Also, maybe an assert should be added when `offline_mode` and `enable_local_evaluation` are True at the same time.

**Comment by matthewelwell** [comment]
Yep, good spot - thanks @AdrianB-sovo. We'll get that fixed up.

**Comment by matthewelwell** [comment]
@AdrianB-sovo I have had a quick look into this and I don't think this is the case. From what I can tell, we only start the poller if `offline_mode==False` (see [here](https://github.com/Flagsmith/flagsmith-python-client/blob/main/flagsmith/flagsmith.py#L100)). Are you able to provide some example code that demonstrates the issue that you're facing?

**Comment by AdrianB-sovo** [comment]
@matthewelwell Yes, sorry, you're right. I should have my eyes checked 🙃.

**Comment by matthewelwell** [comment]
All good!
