### ISSUE TITLE
Openfeature Provider

### ISSUE THREAD

**Issue by graytonio** [Flagsmith/flagsmith-python-client#74]
Are there any plans to implement an Openfeature provider for the python sdk? We would prefer to keep our flagging implementation consistent across applications with using open feature.

**Comment by matthewelwell** [comment]
Hi @graytonio ! Yes, we definitely plan on completing this, in fact, there's an old PR which needs resurrecting [here](https://github.com/open-feature/python-sdk-contrib/pull/2). I'm planning to work on this within the next week!

**Comment by graytonio** [comment]
Looking forward to it 👍

**Comment by khvn26** [comment]
This has been [released](https://github.com/Flagsmith/flagsmith-openfeature-provider-python/releases/tag/v0.1.0) last month.
