### ISSUE TITLE
Async Client

### ISSUE THREAD

**Issue by andrewgy8** [Flagsmith/flagsmith-python-client#8]
Hey! 

Any future plans for an AsyncFlagsmith client? Just curious as we are using FastAPI async code and would like to integrate it into our stack. 

Thanks!

**Comment by dabeeeenster** [comment]
Hi @andrewgy8 - not at the top of the list of things to do I'm afraid - we'd be happy to take PR's/new repos tho! The only thing that would need to be swapped out is the HTTP client I would have thought?

**Comment by andrewgy8** [comment]
Yeah, thats what I was taking a look at. Of all the other feature flag clients out there, your's seems to be the most simple to convert to async. Ill see what we can do. Thanks!
