### ISSUE TITLE
Error when raising `FlagsmithAPIError`

### ISSUE THREAD

**Issue by AdrianB-sovo** [Flagsmith/flagsmith-python-client#98]
The following is not valid:
https://github.com/Flagsmith/flagsmith-python-client/blob/92e19f4e0f152bae063dbeca8e7907fee6ec4913/flagsmith/flagsmith.py#L385-L388

When logging the exception string, the user will always get exactly `Invalid request made to Flagsmith API. Response status code: %d`.

**Comment by AdrianB-sovo** [comment]
Hi @matthewelwell, I'll let the Flagsmith's team do the fix.

**Comment by khvn26** [comment]
Hi @AdrianB-sovo! This has been fixed in release 3.8.0.
